###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
    application:
        name: app-zuul
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


### 配置网关反向代理
zuul:
  routes:
    api-a:
     ### 以 /api-wechat/访问转发
      path: /api-wechat/**
      serviceId: app-wechat
    api-b:
        ### 以 /api-member/访问转发
      path: /api-member/**
      serviceId: app-member


