#logging:
#  level:
#    org.springframework.web: INFO
#    com.github.binarywang.demo.wx.mp: DEBUG
#    me.chanjar.weixin: DEBUG
#wx:
#  mp:
#    configs:
#      - appId: wxc08fba8c6a398ff5 #（一个公众号的appid）
#        secret: f4cc241da6bf2015207dd86f9094dc9a #（公众号的appsecret）
#        token: lamdong #（接口配置里的Token值）
#
#mayikt:
#  weixin:
#    registration:
#       code:
#       ###微信注册码消息
#        message:  您的注册码为:%s，谢谢关注踏雪无痕公众号
#    ###默认提示消息
#    default:
#      registration:
#        code:
#          message: 请输入手机号，获取注册码

spring:
  redis: #Reids配置
    database: 1  # Redis数据库索引（默认为0
    host: 192.168.3.150
    port: 6379  # Redis服务器连接端口
    pool:
      max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 50 # 连接池中的最大空闲连接
      max-wait: 15000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 1 # 连接池中的最小空闲连接

  datasource: # 主数据源，默认的
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.253.137:3306/meite_member?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root


####服务启动端口号
#server:
#  port: 8200
####服务名称(服务注册到eureka名称)
#spring:
#    application:
#        name: app-wechat
####服务注册到eureka地址
#eureka:
#  client:
#    service-url:
#           defaultZone: http://localhost:8100/eureka
#
#swagger:
#  base-package: com.cn.service
#  title: SpringCloud2.x构建微服务电商项目-微信服务接口
#  description: 该项目“基于SpringCloud2.x构建微服务电商项目”
#  version: 1.1
#  terms-of-service-url: www.mayikt.com
#  contact:
#    name: 踏雪无痕
#    email: lamdong520@163.com
