#
#server:
#  port: 8300
#spring:
#    application:
#        name: app-member
#eureka:
#  client:
#    service-url:
#           defaultZone: http://localhost:8100/eureka
#
#####swagger相关配置
#swagger:
#  base-package: com.cn.service
#  title: SpringCloud2.x构建微服务电商项目-会员服务接口
#  description: 该项目“基于SpringCloud2.x构建微服务电商项目”
#  version: 1.1
#  terms-of-service-url: www.mayikt.com
#  contact:
#    name: 踏雪无痕
#    email: lamdong520@163.com
